const crypto=require('crypto');
const express=require('express');
const {z}=require('zod');
const db=require('../db');
const {authenticateToken}=require('../middleware/auth');
const {detectAnomaliesForOrganization}=require('../services/analyticsService');
const router=express.Router(); router.use(authenticateToken);
const id=z.string().uuid();
const recordSchema=z.object({resourceId:id,locationId:id,quantity:z.coerce.number().finite().nonnegative(),unit:z.string().trim().min(1).max(32),cost:z.coerce.number().finite().nonnegative().default(0),recordedAt:z.string().datetime({offset:true}).or(z.string().regex(/^\d{4}-\d{2}-\d{2}$/)),notes:z.string().trim().max(1000).optional().default('')});

router.get('/',async(req,res,next)=>{try{const {search,resourceId,locationId,startDate,endDate,sort='recordedAt',order='desc'}=req.query;const allowedSort={recordedAt:'c."recordedAt"',quantity:'c.quantity',cost:'c.cost',resource:'r.name',location:'l.name'};let sql=`SELECT c.*,l.name AS location,r.name AS resource,r.type AS "resourceType",r.unit AS "resourceUnit" FROM consumption_records c JOIN locations l ON l.id=c."locationId" AND l."organizationId"=c."organizationId" JOIN resources r ON r.id=c."resourceId" AND r."organizationId"=c."organizationId" WHERE c."organizationId"=$1`;const p=[req.user.organizationId];if(search){p.push(`%${search}%`);sql+=` AND (r.name ILIKE $${p.length} OR l.name ILIKE $${p.length} OR coalesce(c.notes,'') ILIKE $${p.length})`}if(resourceId){id.parse(resourceId);p.push(resourceId);sql+=` AND c."resourceId"=$${p.length}`}if(locationId){id.parse(locationId);p.push(locationId);sql+=` AND c."locationId"=$${p.length}`}if(startDate){p.push(startDate);sql+=` AND c."recordedAt">=$${p.length}`}if(endDate){p.push(endDate);sql+=` AND c."recordedAt"<($${p.length}::date + interval '1 day')`}sql+=` ORDER BY ${allowedSort[sort]||allowedSort.recordedAt} ${String(order).toLowerCase()==='asc'?'ASC':'DESC'} LIMIT 500`;res.json({success:true,data:(await db.query(sql,p)).rows})}catch(e){next(e)}});
router.post('/',async(req,res,next)=>{try{const b=recordSchema.parse(req.body);const org=req.user.organizationId;const [loc,resource]=await Promise.all([db.query('SELECT id FROM locations WHERE id=$1 AND "organizationId"=$2',[b.locationId,org]),db.query('SELECT id,unit FROM resources WHERE id=$1 AND "organizationId"=$2',[b.resourceId,org])]);if(!loc.rowCount||!resource.rowCount)return res.status(400).json({success:false,error:{code:'INVALID_REFERENCE',message:'Location or resource does not belong to this organization.'}});const rid=crypto.randomUUID(),now=new Date();const unit=b.unit||resource.rows[0].unit;const r=await db.query('INSERT INTO consumption_records(id,"organizationId","locationId","resourceId",quantity,unit,cost,"recordedAt",notes,"createdAt","updatedAt") VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$10) RETURNING *',[rid,org,b.locationId,b.resourceId,b.quantity,unit,b.cost,b.recordedAt,b.notes,now]);const anomalies=await detectAnomaliesForOrganization(org);res.status(201).json({success:true,data:{...r.rows[0],anomaliesCreated:anomalies.length}})}catch(e){next(e)}});
router.put('/:id',async(req,res,next)=>{try{id.parse(req.params.id);const b=recordSchema.parse(req.body);const org=req.user.organizationId;const [loc,resource]=await Promise.all([db.query('SELECT id FROM locations WHERE id=$1 AND "organizationId"=$2',[b.locationId,org]),db.query('SELECT id,unit FROM resources WHERE id=$1 AND "organizationId"=$2',[b.resourceId,org])]);if(!loc.rowCount||!resource.rowCount)return res.status(400).json({success:false,error:{code:'INVALID_REFERENCE',message:'Location or resource does not belong to this organization.'}});const r=await db.query('UPDATE consumption_records SET "locationId"=$1,"resourceId"=$2,quantity=$3,unit=$4,cost=$5,"recordedAt"=$6,notes=$7,"updatedAt"=$8 WHERE id=$9 AND "organizationId"=$10 RETURNING *',[b.locationId,b.resourceId,b.quantity,b.unit,b.cost,b.recordedAt,b.notes,new Date(),req.params.id,org]);if(!r.rowCount)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Consumption record not found'}});res.json({success:true,data:r.rows[0]})}catch(e){next(e)}});
router.delete('/:id',async(req,res,next)=>{try{id.parse(req.params.id);const r=await db.query('DELETE FROM consumption_records WHERE id=$1 AND "organizationId"=$2 RETURNING id',[req.params.id,req.user.organizationId]);if(!r.rowCount)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Consumption record not found'}});res.json({success:true,data:{id:req.params.id}})}catch(e){next(e)}});
module.exports=router;
